name: lab1
description: Laboratory work 1.
version: 1.0.0
repository: https://github.com/k1nd-cat/software-testing

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
